### ISSUE TITLE
can't make it work on android 4.4.2

### ISSUE THREAD

**Issue by felipestanham** [mofus/Kiosker#10]
I installed the app from playstore, coppied the base.json file, changed the salt, passwordHash and published it in a web server. 
When opening the app and entering the base url always an error is shown.

Could you please guide me

**Comment by mofus** [comment]
It has been a few years since I last worked on this. So I am not sure if I can help, but I will try. What is the error you are getting? Can you provide a screenshot?

**Comment by felipestanham** [comment]
Thnks for your time.

Today I'm not at the office and have no android device to test. But the error screen only says 
"
ERROR
Ok, try again
"

I tried deleting all the app data, different base.json files, but the same error always appears.

My base.json file is hosted at http://pdsfeedback.epizy.com/kiosker/configs/

Regards

**Comment by mofus** [comment]
I get a 403 unauthorized error when I try the link.

**Comment by felipestanham** [comment]
Strange, I just tried from two separate networks. But here is a copy of the file

{
    "home": [{ "url":"http://google.com", "title":"Google"}],
    "sites": [{ "url":"http://itu.dk", "title":"ITU"}],
    "screensavers": [{"url":"http://raphaeljs.com/polar-clock.html", "title":"Polar Clock"}, {"url":"http://www.cafeanalog.dk/", "title":"Cafe Analog"}],
    "layout": 0,
    "screenSavePeriodMins": 30,
    "screenSaveLengthMins": 2,
    "idlePeriodMins": 120,
    "resetToHomeMins": 2,
    "masterPasswordHash": "122bb26fd3bd58cfb273b9b1d42f2d5889d2d94a",
    "masterPasswordSalt": "123",
    "standbyStartTime": "18.00",
    "standbyStopTime": "07.30",
    "reloadPeriodMins": 360,
    "allowSwitching": true,
    "autoCycleSecondary": true,
    "autoCycleSecondaryPeriodMins": 20,
    "errorReloadMins": 5,
    "allowHome": false,
    "volume": 30,
    "mute": false,
    "brightness": 100,
    "dimmedBrightness": 70,
    "quietHoursStartTime": "18.00",
    "quietHoursStopTime": "07.30"
}

**Comment by mofus** [comment]
Try removing the first screensaver - "http://raphaeljs.com/polar-clock.html" - that link seems to be dead. Also make sure that your hash and salt's are correct.

**Comment by felipestanham** [comment]
Clearly there is something wrong with my hosting server, I hosted the file in dropbox and that error disappeared.
This is my base.json new location
https://dl.dropboxusercontent.com/u/836829/base.json

Now, another error appeares saying "Sorry - wrror while downloading. Wrong base url?"
The log shows "error while trying to show navitation ui" "java.io.IOException: Error running exec(). Command" at .... at "dk.itu.kiosker.activities.HardwareController.showNavitationUI(HardwareController.java:55)"

**Comment by mofus** [comment]
is your device rooted? If it's not that could trigger that error

**Comment by felipestanham** [comment]
Apperently I have to add the device specific settings file. I gave my device a name and created the device json file and it started working.

Now I can't seem to make it work in landscape mode nor disable the home button. I used Kingo Root to root my device.

**Comment by mofus** [comment]
Glad to hear that you got it working. Landscape mode is not supported in the app. I don't know Kingo Root, so I am unsure if it works as needed. Have you looked at the [suggested configuration here](https://github.com/mofus/Kiosker/wiki/Suggested-configuration-for-Nexus-7-devices)?
